version: "3.9"

services:
  jasper-app:
    image: jasper-app-last:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /external-reports/config.json
      REPORT_DIRECTORY: /external-reports
    volumes:
      - ./templ:/external-reports